language: node_js
before_script:
  - npm install -g gatsby-cli
  - npm install -g eslint
  - npm install gh-pages
  - npm install
node_js:
  - "10"

script:
  # ensure these pass before merge into dev/master
  - eslint "**/*.js"
  - npm run build
  - npm run test

deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: npm run-script deploy
  skip_cleanup: true
  on:
    branch: master
