language: node_js
before_script:
  - npm install -g gatsby-cli
  - npm install -g prettier
  - npm install gh-pages
node_js:
  - "10"

script:
  # check for syntax standards
  - prettier --check "**/*.js"

  # check to see if it builds
  - npm run build

deploy:
  provider: script
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script: npm run-script deploy
  skip_cleanup: true
  on:
    branch: master
